#!/bin/bash
set -e

source local-configuration/lib-system-checks.sh

check_branch_name() {
  BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
  PATTERN='^(feature|task|bugfix)\/BU-[0-9]+-([a-zA-Z0-9]|-)*[a-zA-Z0-9]+$'
  if ! echo "$BRANCH_NAME" | LC_ALL=en_US.UTF-8 grep -qE "$PATTERN"; then
    echo "The branch name is invalid. Please, rewrite it according to the conventions."
    return 1
  fi
}

per_file_check() {
  for file in $(git diff --cached --name-only); do
    if [ -f "$file" ]; then
      if check_commands terraform --silent && [[ "$file" =~ (.*)\.tfvars|(.*)\.tf|(.*)\.tftest\.hcl ]]; then
        echo "Formatting terraform: $file"
        # shellcheck disable=SC2015
        terraform fmt -no-color -list=false "$file" && git add "$file" || true
      fi
    fi
  done
}

echo "Pre-commit githook triggered... "
check_branch_name
per_file_check
