#!/bin/bash
set -e

check_branch_name() {
  BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
  PATTERN='^(feature|task|bugfix)\/BU-[0-9]+-([a-zA-Z0-9]|-)*[a-zA-Z0-9]+$'
  if ! echo "$BRANCH_NAME" | LC_ALL=en_US.UTF-8 grep -qE "$PATTERN"; then
    echo "The branch name is invalid. Please, rewrite it according to the conventions."
    return 1
  fi
}

echo "Pre-commit githook triggered... "
check_branch_name
